In [225]:
import numpy as np
import pandas as pd

In [ ]:
1.  How likely is it that you roll doubles when rolling two dice?

In [500]:
die_outcomes = [1, 2, 3, 4, 5, 6]

n_dice = 2
n_simulations = 100000

equals_list = []
rolls = np.random.choice(die_outcomes, (n_simulations, n_dice))

for roll in rolls:
    if roll[0] == roll[1]:
        equals_list.append(1)
    else:
        equals_list.append(0)
    
doubles = sum(equals_list)/n_simulations
doubles

0.1647

In [501]:
# def doubles():  I tried to vectorize a function
#     for roll in rolls:
#         for i in rolls:
#             if rolls.i[0] == i[1]:
#                 return True
#             else:
#                 return False

# rolls.apply(doubles(), axis=1)

2.  If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [502]:
coin_outcomes = ['H', 'T']

n_trials = 8
n_simulations = 100000

eight_flips = np.random.choice(coin_outcomes, (n_simulations, n_trials))
eight_flips

array([['T', 'T', 'T', ..., 'H', 'H', 'T'],
       ['T', 'T', 'H', ..., 'H', 'H', 'H'],
       ['T', 'H', 'H', ..., 'H', 'T', 'H'],
       ...,
       ['T', 'H', 'H', ..., 'H', 'H', 'H'],
       ['H', 'H', 'H', ..., 'H', 'T', 'H'],
       ['T', 'H', 'T', ..., 'H', 'T', 'T']], dtype='<U1')

In [503]:
n_heads = (eight_flips == 'H').sum(axis=1)
(n_heads == 3).mean()

0.21865

In [504]:
(n_heads >= 3).mean()

0.85486

3.  There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [505]:
billboard_outcomes = ['DS', 'WD']
outcome_probabilities = [.25, .75]

n_billboards = 2
n_simulations = 100000
whose_face = np.random.choice(billboard_outcomes, (n_simulations, n_billboards), p = outcome_probabilities)
whose_face

array([['WD', 'DS'],
       ['WD', 'WD'],
       ['WD', 'WD'],
       ...,
       ['WD', 'WD'],
       ['DS', 'WD'],
       ['WD', 'WD']], dtype='<U2')

In [506]:
data_science = (whose_face == 'DS').sum(axis=1)
data_science

array([1, 0, 0, ..., 0, 1, 0])

In [44]:
(data_science == 2).mean()

0.06288

4. Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal) You'll need to make a judgement call on how to handle some of your values

In [175]:
pop_tart_usage_per_week = np.random.normal(3, 1.5, (n_simulations, 5))
n_simulations = 100000
pop_tart_usage_per_week

array([[4.81677327, 4.12129586, 2.54628636, 2.09845901, 2.04564672],
       [3.53995133, 2.20608336, 1.25460265, 4.0032354 , 3.35550636],
       [4.86197932, 5.88097925, 1.90779617, 2.33934823, 4.0801409 ],
       ...,
       [4.51440919, 3.0573304 , 2.25610844, 1.47807864, 1.95330572],
       [1.69165209, 4.40792671, 2.09727388, 3.77303195, 3.01052273],
       [3.60275305, 2.65837125, 4.03106243, 3.63907162, 4.72937841]])

In [177]:
(pop_tart_usage_per_week.sum(axis=1) <= 16).mean()

0.61773

5.  Men have an average height of 178 cm and standard deviation of 8cm.
Women have a mean of 170, sd = 6cm.
Since you have means and standard deviations, you can use np.random.normal to generate observations.
If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?


In [191]:
n_simulations = 100000
men_height = np.random.normal(178, 8, n_simulations)
women_height = np.random.normal(170, 6, n_simulations)

count = 0
i = 0
for i in range(n_simulations):
    if women_height[i] > men_height[i]:
        count += 1
        i += 1
    else:
        i += 1
count

chances_woman_is_taller = count / n_simulations
chances_woman_is_taller

0.21187

6.  When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails5. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

In [106]:
failure = [False, True]
chances = [249/250, 1/250]
n_installations = 50
n_simulations = 100000
fifty_installations = np.random.choice(failure, (n_simulations, n_installations), p = chances)
fifty_installations

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [119]:
(fifty_installations.sum(axis=1) == 0).mean()

0.81842

In [120]:
n_installations = 100
one_hundred_installations = np.random.choice(failure, (n_simulations, n_installations), p = chances)
(one_hundred_installations.sum(axis=1) == 0).mean()

0.67195

What is the probability that we observe an installation issue within the first 150 students that download anaconda?

probability that we observe an installation issue within the first 150 students equals

1 - the probability that there are no issues

In [174]:
n_installations = 150
one_hundred_fifty_installations = np.random.choice(failure, (n_simulations, n_installations), p=chances)
issue = 1 - (one_hundred_fifty_installations.sum(axis=1) == 0).mean()
issue

0.45324

How likely is it that 450 students all download anaconda without an issue?

In [122]:
n_installations = 450
four_hundred_fifty_installations = np.random.choice(failure, (n_simulations, n_installations), p = chances)
(four_hundred_fifty_installations.sum(axis=1) == 0).mean()

0.16606

In [ ]:
There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

In [157]:
food_truck = [True, False]
probability = [.7, .3]

days = 3
n_simulations = 100000

im_hungry = np.random.choice(food_truck, (n_simulations, days), p = probability)
(im_hungry.sum(axis=1) == 0).mean()

0.02668

In [143]:
How likely is it that a food truck will show up sometime this week?

Object `week` not found.


In [162]:
days = 7

im_hungry = np.random.choice(food_truck, (n_simulations, days), p = probability)
(im_hungry.sum(axis=1) == 0).mean() #will spit out probabiliy that trucks will not show all week
im_not_hungry = 1 - (im_hungry.sum(axis=1) == 0).mean()
im_not_hungry

0.99979

In [156]:
If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

SyntaxError: unterminated string literal (detected at line 1) (2650225207.py, line 1)

In [355]:
n = 23
n_simulations = 1000000
birthdays = list(range(0, 365))
probabilities = [1/365 for birthday in birthdays]

list_of_possible_classes = np.random.choice(birthdays, (n_simulations, n), p = probabilities)
list_of_possible_classes_df = pd.DataFrame(list_of_possible_classes)

(list_of_possible_classes_df.nunique(axis=1) != 23).mean()






0.507511

In [470]:
# The wizard will win with an expected value of each roll being 2.5 times 6 rolls giving an expected value of 15
# while the mage has 4 rolls with an expected value of 3.5 giving a total expected value of 14
def duel(number) -> 'type in the number of simulations you want':
    n_simulations = number
    # wizard rolls 6d4 or six 4 sided dice
    wizard_list = [1, 2, 3, 4]
    n_wizard_rolls = 6
    # mage rolls 4d6 or 4 six sided dice
    mage_list = [1, 2, 3, 4, 5, 6]
    n_mage_rolls = 4

    wizard_sum = np.random.choice(wizard_list, (n_simulations, n_wizard_rolls)).sum(axis=1)
    mage_sum = np.random.choice(wizard_list, (n_simulations, n_wizard_rolls)).sum(axis=1)

    wizard_win_count = 0
    mage_win_count = 0
    tie_count = 0
    i=0
    for _ in range(n_simulations):
        if wizard_sum[_] > mage_sum[_]:
            wizard_win_count += 1
        elif mage_sum[_] > wizard_sum[_]:
            mage_win_count += 1
        else:
            tie_count += 1
        
    print(f'The wizard wins {wizard_win_count/n_simulations * 100} percent of the time')
    print(f'The mage wins {mage_win_count/n_simulations * 100} percent of the time')
    print(f'They tie {tie_count/n_simulations} percent of the time')

In [474]:
duel(10)

The wizard wins 50.0 percent of the time
The mage wins 10.0 percent of the time
They tie 0.4 percent of the time


Running this multiple times gives highly variable answers with 10 battles

In [460]:
duel(10)

The wizard wins 20.0 percent of the time
The mage wins 50.0 percent of the time
They tie 0.3 percent of the time


In [461]:
duel(100)

The wizard wins 45.0 percent of the time
The mage wins 43.0 percent of the time
They tie 0.12 percent of the time


In [462]:
duel(100)

The wizard wins 47.0 percent of the time
The mage wins 44.0 percent of the time
They tie 0.09 percent of the time


In [463]:
duel(10000)

The wizard wins 44.83 percent of the time
The mage wins 44.45 percent of the time
They tie 0.1072 percent of the time


In [464]:
duel(10000)

The wizard wins 44.87 percent of the time
The mage wins 44.82 percent of the time
They tie 0.1031 percent of the time


In [465]:
duel(10000)

The wizard wins 44.440000000000005 percent of the time
The mage wins 45.31 percent of the time
They tie 0.1025 percent of the time


In [466]:
#There doesn't seem to be a clear winner and we need more statistical methods to determine

In [467]:
duel(1000000)

The wizard wins 44.9383 percent of the time
The mage wins 44.934400000000004 percent of the time
They tie 0.101273 percent of the time


In [468]:
duel(1000000)

The wizard wins 45.0523 percent of the time
The mage wins 44.794200000000004 percent of the time
They tie 0.101535 percent of the time


In [469]:
duel(1000000)

The wizard wins 44.9242 percent of the time
The mage wins 44.9306 percent of the time
They tie 0.101452 percent of the time


Simulating Chuck a Luck

In [548]:
#def wins(num_simulations):
num_simulations = 10000
player_balance = -1
player_choice = np.random.choice([1, 2, 3, 4, 5, 6])

dice = 3
values = [1, 2, 3, 4, 5, 6]
simulations = num_simulations

results = np.random.choice(values, (simulations, dice))
number_correct = (results == player_choice).sum(axis=1)
payout = np.unique(number_correct - 1, return_counts = True)

print(f'Your chances of getting paid ${payout[0][0]} are {payout[1][0]/num_simulations} and your estimated expected loss from this outcome is ${payout[0][0] * payout[1][0]}.')
print(f'Your chances of getting paid ${payout[0][1]} are {payout[1][1]/num_simulations} and your estimated expected payoff from this outcome is ${payout[0][1] * payout[1][1]}.')
print(f'Your chances of getting paid ${payout[0][2]} are {payout[1][2]/num_simulations} and your estimated expected payoff from this outcome is ${payout[0][2] * payout[1][2]}.')
print(f'Your chances of getting paid ${payout[0][3]} are {payout[1][3]/num_simulations} and your estimater expected payoff from this outcome is ${payout[0][3] * payout[1][3]}.')
print(f'Your average payout across {num_simulations} simulations is {payout[0][0] * payout[1][0]/num_simulations + payout[0][0] * payout[1][0]/num_simulations + payout[0][0] * payout[1][0]/num_simulations + payout[0][0] * payout[1][0]/num_simulations}!')

Your chances of getting paid $-1 are 0.5787 and your estimated expected loss from this outcome is $-5787.
Your chances of getting paid $0 are 0.3471 and your estimated expected payoff from this outcome is $0.
Your chances of getting paid $1 are 0.0687 and your estimated expected payoff from this outcome is $687.
Your chances of getting paid $2 are 0.0055 and your estimater expected payoff from this outcome is $110.
Your average payout across 10000 simulations is -2.3148!


In [512]:
number_correct = (results == player_choice).sum(axis=1)
number_correct

array([0, 0, 0, 0, 1, 1, 0, 0, 1, 2])

In [521]:
payout = number_correct - 1

In [534]:
payout

(array([-1,  0,  1,  2]), array([5756, 3521,  661,   62]))

In [530]:
np.unique(payout, return_counts = True)

(array([-1,  0,  1]), array([6, 3, 1]))

In [543]:
payout[1][1]

3528